name: "Vercel Alias"
description: "Create a predictable alias URL for a Vercel deployment and optionally finish GitHub deployment"

inputs:
  vercel-token:
    description: "Vercel authentication token"
    required: true
  vercel-org-id:
    description: "Vercel team/org ID (for --scope)"
    required: true
  deployment-url:
    description: "Vercel deployment URL to alias"
    required: true
  app-name:
    description: "App identifier (web, platform, site, docs)"
    required: true
  job-ref:
    description: "Job reference identifier (e.g., pr-123, staging)"
    required: true
  preview-domain:
    description: "Preview domain (e.g., vm6.ai)"
    required: true
  deployment-id:
    description: "GitHub deployment ID (if provided, will finish the deployment with alias URL)"
    required: false
    default: ""
  deployment-env:
    description: "GitHub deployment environment name (required if deployment-id is provided)"
    required: false
    default: ""

outputs:
  url:
    description: "The aliased URL"
    value: ${{ steps.alias.outputs.url }}

runs:
  using: "composite"
  steps:
    - name: Create Vercel alias
      id: alias
      shell: bash
      run: |
        # Build alias URL: {job-ref}-{app}.{preview-domain}
        ALIAS_URL="${{ inputs.job-ref }}-${{ inputs.app-name }}.${{ inputs.preview-domain }}"

        echo "Creating alias: ${ALIAS_URL} -> ${{ inputs.deployment-url }}"

        # Set the alias using Vercel CLI
        vercel alias set "${{ inputs.deployment-url }}" "${ALIAS_URL}" \
          --token="${{ inputs.vercel-token }}" \
          --scope="${{ inputs.vercel-org-id }}"

        # Output the full URL
        FULL_URL="https://${ALIAS_URL}"
        echo "url=${FULL_URL}" >> $GITHUB_OUTPUT
        echo "Alias created: ${FULL_URL}"

    - name: Finish GitHub deployment
      if: inputs.deployment-id != ''
      uses: bobheadxi/deployments@v1
      with:
        step: finish
        token: ${{ github.token }}
        status: success
        env: ${{ inputs.deployment-env }}
        env_url: ${{ steps.alias.outputs.url }}
        deployment_id: ${{ inputs.deployment-id }}
